Update deploy.yml
Add check for SONAR_TOKEN presence in deploy workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,7 +33,14 @@ jobs:
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       run: |
-        
+        if [ -z "$SONAR_TOKEN" ]; then
+        echo "TOKEN MISSING"
+        exit 1
+
+        else
+        echo "TOKEN FOUND"
+         fi
+         
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.token="$secrets.SONAR_TOKEN" \
          -Dsonar.organization=Harshitha-b01 \ 
